# -*- coding: utf-8 -*-
"""Resume_Parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LY03g8xDJsCym0UkG3qMEO4EBYrkfprH
"""

# prompt: Write a ChatGPT Prompt which takes your Resume as input and parse the content in JSON format.

"""
I have a resume in plain text format. I want you to act as a resume parser and extract the information from the resume and provide it to me in a structured JSON format.

Here is the resume:
\"\"\"
[ RESUME CONTENT HERE]


The JSON should have the following keys:
- name
- email
- phone
- linkedin
- github
- skills
- experience
- education
- personal_interests
- awards
- certifications
- publications
- projects
- references

For the experience, education, awards, certifications, publications, and projects sections, please provide an array of objects with the following keys:
- title
- company
- years
- description

For the skills section, please provide an array of strings.
For the personal_interests section, please provide an array of strings.
For the references section, please provide an array of objects with the following keys:
- name
- title
- company
- email
- phone

Please try your best to extract all the information from the resume. If you are unable to find a piece of information, please leave the corresponding value as an empty string.
"""